language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - make test
  - coverage run --source=loveletter loveletter/setup.py test
after_success:
  - coveralls
